### ISSUE TITLE
Made an edit that upgrades the cobblestone mining function (for vanilla skyblock)

### ISSUE THREAD

**Issue by Kyu** [Scripter17/Minecraft-Hotkeys#8]
It now mines a single cobble block, waits, the mines again. It also assumes your hotbar is full of stone pickaxes and mines with each stone pickaxe so you can spend more time afk.

https://gist.github.com/Kyu/22e15de747aaf0775752563e23062555 

Diff: 
```diff
@@ -181,9 +181,19 @@
 		GuiControl, , CurrentAction, Cobblestone
 		Suspend, On
 		isDoingSomething:=True
+		weaponSlot:=1
+
 		while (stopCurrent<>True){
+			Sleep, 1000
 			ControlClick, , ahk_pid %WindowPID%, , Left, , NAD
-			Sleep, 100
+			Sleep, 900
+			ControlClick, , ahk_pid %WindowPID%, , Left, , NAU
+			weaponSlot++
+			if (weaponSlot = 10) {
+				weaponSlot := 0
+			}
+			Send %weaponSlot%
+			Sleep, 2000
 		}
 		ControlClick, , ahk_pid %WindowPID%, , Left, , NAU
 		stopCurrent:=False
@@ -250,4 +260,6 @@
 !+^#esc::
 	; Just trust me on this
 	ExitApp
-return
\ No newline at end of file
+return
```

**Comment by Scripter17** [comment]
Unfortunately I haven't played minecraft, used this script, or used windows for much of anything for about a year or two

I booted into windows to test this and I should get back to you in about an hour once I remember how to do anything in this OS

**Comment by Kyu** [comment]
> Unfortunately I haven't played minecraft, used this script, or used windows for much of anything for about a year or two

Haha life is funny like that. Thanks for making this script though!
